### ISSUE TITLE
Unable to compile PHP 5.6 on aarch64 in AlmaLinux 9.3

### ISSUE THREAD

**Issue by aik099** [shivammathur/php-src-backports#2]
**Describe the bug**

Attempt to compile PHP 5.6 on AlmaLinux 9.3 on aarch64 results in this error:
```
/bin/sh /usr/src/php-5.6/libtool --silent --preserve-dup-deps --mode=compile cc  -IZend/ -I/usr/src/php-5.6/Zend/ -DPHP_ATOM_INC -I/usr/src/php-5.6/include -I/usr/src/php-5.6/main -I/usr/src/php-5.6 -I/usr/src/php-5.6/ext/date/lib -I/usr/src/php-5.6/ext/ereg/regex -I/usr/include/libxml2 -I/usr/src/php-5.6/ext/mbstring/oniguruma -I/usr/src/php-5.6/ext/mbstring/libmbfl -I/usr/src/php-5.6/ext/mbstring/libmbfl/mbfl -I/usr/src/php-5.6/ext/sqlite3/libsqlite -I/usr/src/php-5.6/TSRM -I/usr/src/php-5.6/Zend    -I/usr/include -g -O2 -fvisibility=hidden  -c /usr/src/php-5.6/Zend/zend_operators.c -o Zend/zend_operators.lo 
/tmp/ccaqQeJY.s: Assembler messages:
/tmp/ccaqQeJY.s:6629: Error: operand 2 must be an integer register -- `mul x2,v0,v1'
/tmp/ccaqQeJY.s:6630: Error: operand 2 must be an integer register -- `smulh x0,v0,v1'
/tmp/ccaqQeJY.s:7341: Error: operand 2 must be an integer register -- `mul x2,v9,v0'
/tmp/ccaqQeJY.s:7342: Error: operand 2 must be an integer register -- `smulh x1,v9,v0'
/tmp/ccaqQeJY.s:7488: Error: operand 2 must be an integer register -- `mul x2,v0,v0'
/tmp/ccaqQeJY.s:7489: Error: operand 2 must be an integer register -- `smulh x1,v0,v0'
make: *** [Makefile:1633: Zend/zend_operators.lo] Error 1
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest version.

**Operating systems**

AlmaLinux 9.3 aarch64

**To Reproduce**

1. checkout this repository
2. go to the folder with a checkout
3. run the `git checkout 5.6.40` command
4. run the `CFLAGS="-Wno-implicit-function-declaration"` command
5. run the `./buildconf --force` command
6. install missing development packages (in my case I've used `dnf install libxml2-devel bzip2-devel libcurl-devel libpng-devel libicu-devel libmcrypt-devel readline-devel` command)
7. run the `./configure --prefix=/usr/local/php-5.6 --enable-fpm --with-fpm-user=apache --with-fpm-group=apache --with-openssl --with-zlib --with-bz2 --with-curl --enable-exif --with-gd --with-gettext --with-mhash --enable-mbstring --with-mcrypt  --with-mysql --with-mysqli --enable-opcache --enable-pcntl --with-pdo-mysql --with-readline --enable-soap --enable-sockets --enable-shmop --enable-sysvmsg --with-pear` command
8. run `make` command

**Expected behavior**

The output should end with these lines:
```
Generating phar.php
Generating phar.phar
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
clicommand.inc
directorygraphiterator.inc
directorytreeiterator.inc
invertedregexiterator.inc
pharcommand.inc
phar.inc

Build complete.
Don't forget to run 'make test'.
```

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

The problem is already solved in PHP 7.2.0 in https://github.com/php/php-src/commit/8c8679207ae5ada8751288e75b78c928a4d34d1d commit, which needs to be backported. Originally reported in https://bugs.php.net/bug.php?id=70015 .

**Comment by shivammathur** [comment]
@aik099 
Added in https://github.com/shivammathur/php-src-backports/commit/76a892a03b23f07f9061f56b3c75c6ecf4f596e7
